# nix/gitops/env/pdns.nix
#
# PowerDNS Authoritative DNS — per-node authoritative DNS for public
# domains (seddon.ca, xtcp.io), backed by the CNPG PostgreSQL cluster.
#
# Topology:
#
#   External DNS query (port 53 UDP+TCP)
#     → VIP 10.33.33.52 (Cilium L2 LoadBalancer)
#     → PowerDNS DaemonSet pod (hostNetwork, every node)
#     → PostgreSQL backend (pg-rw.postgres.svc.cluster.local)
#
#   cert-manager ACME DNS-01
#     → RFC2136 update (TSIG) → PowerDNS VIP
#     → TXT record written to PG → Let's Encrypt validates
#
# Secrets (pdns-credentials) are pre-generated by nix/secrets.nix and
# applied at bootstrap. PG password is patched live from pg-app (same
# pattern as matrix-secrets).
#
{ pkgs, lib }:
let
  constants = import ../../constants.nix;
  p = constants.pdns;

  # ── PowerDNS Auth 4.9 PostgreSQL schema ───────────────────────────
  # Standard upstream schema from:
  #   https://doc.powerdns.com/authoritative/backends/generic-postgresql.html
  # Plus seed data: SOA + NS records for each managed domain.
  # All DDL is idempotent (IF NOT EXISTS / ON CONFLICT DO NOTHING).
  schemaSql = ''
    -- PowerDNS Auth 4.9 gpgsql schema
    CREATE TABLE IF NOT EXISTS domains (
      id                  SERIAL PRIMARY KEY,
      name                VARCHAR(255) NOT NULL,
      master              VARCHAR(128) DEFAULT NULL,
      last_check          INT DEFAULT NULL,
      type                VARCHAR(8) NOT NULL DEFAULT 'NATIVE',
      notified_serial     BIGINT DEFAULT NULL,
      account             VARCHAR(40) DEFAULT NULL,
      options             TEXT DEFAULT NULL,
      catalog             TEXT DEFAULT NULL,
      CONSTRAINT c_lowercase_name UNIQUE (name)
    );

    CREATE INDEX IF NOT EXISTS rec_name_index ON domains(name);

    CREATE TABLE IF NOT EXISTS records (
      id                  BIGSERIAL PRIMARY KEY,
      domain_id           INT DEFAULT NULL REFERENCES domains(id) ON DELETE CASCADE,
      name                VARCHAR(255) DEFAULT NULL,
      type                VARCHAR(10) DEFAULT NULL,
      content             VARCHAR(65535) DEFAULT NULL,
      ttl                 INT DEFAULT NULL,
      prio                INT DEFAULT NULL,
      disabled            BOOL DEFAULT 'f',
      ordername           VARCHAR(255),
      auth                BOOL DEFAULT 't'
    );

    CREATE INDEX IF NOT EXISTS nametype_index ON records(name, type);
    CREATE INDEX IF NOT EXISTS domain_id ON records(domain_id);
    CREATE INDEX IF NOT EXISTS records_ordername ON records(ordername);

    CREATE TABLE IF NOT EXISTS supermasters (
      ip                  INET NOT NULL,
      nameserver          VARCHAR(255) NOT NULL,
      account             VARCHAR(40) NOT NULL DEFAULT ${"''"},
      PRIMARY KEY (ip, nameserver)
    );

    CREATE TABLE IF NOT EXISTS comments (
      id                  SERIAL PRIMARY KEY,
      domain_id           INT NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
      name                VARCHAR(255) NOT NULL,
      type                VARCHAR(10) NOT NULL,
      modified_at         INT NOT NULL,
      account             VARCHAR(40) DEFAULT NULL,
      comment             TEXT NOT NULL
    );

    CREATE INDEX IF NOT EXISTS comments_name_type_idx ON comments(name, type);
    CREATE INDEX IF NOT EXISTS comments_order_idx ON comments(domain_id, modified_at);

    CREATE TABLE IF NOT EXISTS domainmetadata (
      id                  SERIAL PRIMARY KEY,
      domain_id           INT NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
      kind                VARCHAR(32),
      content             TEXT
    );

    CREATE INDEX IF NOT EXISTS domainidmetaindex ON domainmetadata(domain_id);

    CREATE TABLE IF NOT EXISTS cryptokeys (
      id                  SERIAL PRIMARY KEY,
      domain_id           INT NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
      flags               INT NOT NULL DEFAULT 0,
      active              BOOL DEFAULT 't',
      published           BOOL DEFAULT 't',
      content             TEXT
    );

    CREATE INDEX IF NOT EXISTS domainidindex ON cryptokeys(domain_id);

    CREATE TABLE IF NOT EXISTS tsigkeys (
      id                  SERIAL PRIMARY KEY,
      name                VARCHAR(255),
      algorithm           VARCHAR(50),
      secret              VARCHAR(255),
      CONSTRAINT c_lowercase_name_algorithm UNIQUE (name, algorithm)
    );

    -- ── Seed domains ─────────────────────────────────────────────────
    ${lib.concatMapStringsSep "\n" (domain: ''
    INSERT INTO domains (name, type)
      VALUES ('${domain}', 'NATIVE')
      ON CONFLICT DO NOTHING;
    '') p.domains}

    -- ── Seed SOA + NS records ────────────────────────────────────────
    ${lib.concatMapStringsSep "\n" (domain: ''
    INSERT INTO records (domain_id, name, type, content, ttl, auth)
      SELECT id, '${domain}', 'SOA',
             'ns1.${domain}. ops.${domain}. 1 10800 3600 604800 300',
             300, TRUE
      FROM domains WHERE name = '${domain}'
      ON CONFLICT DO NOTHING;

    INSERT INTO records (domain_id, name, type, content, ttl, auth)
      SELECT id, '${domain}', 'NS', 'ns1.${domain}.', 300, TRUE
      FROM domains WHERE name = '${domain}'
      ON CONFLICT DO NOTHING;
    '') p.domains}
  '';

  # ── pdns.conf (PowerDNS config) ─────────────────────────────────
  pdnsConf = ''
    launch=gpgsql
    gpgsql-host=pg-rw.postgres.svc.cluster.local
    gpgsql-port=5432
    gpgsql-dbname=${p.database}
    gpgsql-user=${p.pgUser}
    gpgsql-password=$(PG_PASSWORD)
    gpgsql-extra-connection-parameters=connect_timeout=5

    local-address=0.0.0.0
    local-port=${toString p.dnsPort}

    # RFC2136 dynamic updates (for cert-manager ACME DNS-01 via TSIG)
    dnsupdate=yes
    allow-dnsupdate-from=10.244.0.0/16,10.96.0.0/12,10.33.33.0/24

    # API (health checks + management)
    api=yes
    api-key=$(API_KEY)
    webserver-address=0.0.0.0
    webserver-port=${toString p.apiPort}
    webserver-allow-from=10.244.0.0/16,10.96.0.0/12,10.33.33.0/24,127.0.0.0/8

    # Logging
    loglevel=4
    log-dns-queries=no
  '';
in
{
  manifests = [
    # ─── CNPG Database CR (creates pdns database in existing PG cluster) ─
    {
      name = "pdns/database.yaml";
      content = ''
        apiVersion: postgresql.cnpg.io/v1
        kind: Database
        metadata:
          name: pdns
          namespace: postgres
          annotations:
            argocd.argoproj.io/sync-wave: "0"
        spec:
          name: ${p.database}
          owner: ${p.pgUser}
          cluster:
            name: pg
      '';
    }

    # ─── Schema DDL ConfigMap ─────────────────────────────────────────
    {
      name = "pdns/configmap-schema-ddl.yaml";
      content = ''
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: pdns-schema-ddl
          namespace: ${p.namespace}
          annotations:
            argocd.argoproj.io/sync-wave: "1"
          labels:
            app.kubernetes.io/name: pdns-schema-bootstrap
            app.kubernetes.io/part-of: pdns
        data:
          bootstrap.sql: |
            ${lib.replaceStrings [ "\n" ] [ "\n            " ] (lib.removeSuffix "\n" schemaSql)}
      '';
    }

    # ─── Placeholder credentials Secret ───────────────────────────────
    # Bootstrap module patches pg-password from pg-app Secret.
    # ArgoCD ignoreDifferences prevents reverting to placeholder.
    {
      name = "pdns/secret-credentials.yaml";
      content = ''
        apiVersion: v1
        kind: Secret
        metadata:
          name: pdns-credentials
          namespace: ${p.namespace}
        type: Opaque
        stringData:
          api-key: "__BOOTSTRAPPED_OUT_OF_BAND__"
          tsig-secret: "__BOOTSTRAPPED_OUT_OF_BAND__"
          pg-password: "__BOOTSTRAPPED_OUT_OF_BAND__"
      '';
    }

    # ─── Schema bootstrap Job ─────────────────────────────────────────
    # Applies the PowerDNS PostgreSQL schema + seed domain records.
    {
      name = "pdns/job-schema-bootstrap.yaml";
      content = ''
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: pdns-schema-bootstrap
          namespace: ${p.namespace}
          annotations:
            argocd.argoproj.io/sync-wave: "2"
            argocd.argoproj.io/hook: Sync
            argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
          labels:
            app.kubernetes.io/name: pdns-schema-bootstrap
            app.kubernetes.io/part-of: pdns
        spec:
          backoffLimit: 10
          template:
            metadata:
              labels:
                app.kubernetes.io/name: pdns-schema-bootstrap
            spec:
              restartPolicy: OnFailure
              containers:
              - name: psql
                image: ghcr.io/cloudnative-pg/postgresql:16.4
                command:
                - sh
                - -c
                - |
                  PGPASSWORD="$PG_PASSWORD" psql \
                    -h pg-rw.postgres.svc.cluster.local \
                    -U ${p.pgUser} \
                    -d ${p.database} \
                    -f /sql/bootstrap.sql
                env:
                - name: PG_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pdns-credentials
                      key: pg-password
                volumeMounts:
                - name: sql
                  mountPath: /sql
                  readOnly: true
              volumes:
              - name: sql
                configMap:
                  name: pdns-schema-ddl
      '';
    }

    # ─── TSIG bootstrap Job ───────────────────────────────────────────
    # Inserts the TSIG key into PowerDNS's tsigkeys table and adds
    # TSIG-ALLOW-DNSUPDATE domain metadata so RFC2136 updates for
    # ACME challenges are accepted with TSIG authentication.
    {
      name = "pdns/job-tsig-bootstrap.yaml";
      content = ''
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: pdns-tsig-bootstrap
          namespace: ${p.namespace}
          annotations:
            argocd.argoproj.io/sync-wave: "3"
            argocd.argoproj.io/hook: Sync
            argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
          labels:
            app.kubernetes.io/name: pdns-tsig-bootstrap
            app.kubernetes.io/part-of: pdns
        spec:
          backoffLimit: 10
          template:
            metadata:
              labels:
                app.kubernetes.io/name: pdns-tsig-bootstrap
            spec:
              restartPolicy: OnFailure
              containers:
              - name: psql
                image: ghcr.io/cloudnative-pg/postgresql:16.4
                command:
                - sh
                - -c
                - |
                  PGPASSWORD="$PG_PASSWORD" psql \
                    -h pg-rw.postgres.svc.cluster.local \
                    -U ${p.pgUser} \
                    -d ${p.database} \
                    -c "INSERT INTO tsigkeys (name, algorithm, secret)
                        VALUES ('${p.tsigKeyName}', '${p.tsigAlgorithm}', '$TSIG_SECRET')
                        ON CONFLICT (name, algorithm) DO UPDATE SET secret = EXCLUDED.secret;"

                  # Allow TSIG-authenticated RFC2136 updates for each domain
                  for DOMAIN in ${lib.concatStringsSep " " p.domains}; do
                    PGPASSWORD="$PG_PASSWORD" psql \
                      -h pg-rw.postgres.svc.cluster.local \
                      -U ${p.pgUser} \
                      -d ${p.database} \
                      -c "INSERT INTO domainmetadata (domain_id, kind, content)
                          SELECT id, 'TSIG-ALLOW-DNSUPDATE', '${p.tsigKeyName}'
                          FROM domains WHERE name = '$DOMAIN'
                          AND NOT EXISTS (
                            SELECT 1 FROM domainmetadata
                            WHERE domain_id = domains.id
                              AND kind = 'TSIG-ALLOW-DNSUPDATE'
                              AND content = '${p.tsigKeyName}'
                          );"
                  done
                env:
                - name: PG_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pdns-credentials
                      key: pg-password
                - name: TSIG_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: pdns-credentials
                      key: tsig-secret
      '';
    }

    # ─── PowerDNS config ConfigMap ────────────────────────────────────
    {
      name = "pdns/configmap-config.yaml";
      content = ''
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: pdns-config
          namespace: ${p.namespace}
          annotations:
            argocd.argoproj.io/sync-wave: "3"
        data:
          pdns.conf: |
            ${lib.replaceStrings [ "\n" ] [ "\n            " ] (lib.removeSuffix "\n" pdnsConf)}
      '';
    }

    # ─── PowerDNS DaemonSet ───────────────────────────────────────────
    # Runs on every node (hostNetwork, port 53). The PG password is
    # injected via an init container that templates pdns.conf from
    # the ConfigMap + Secret (PowerDNS 4.9 does not reliably support
    # PDNS_ env var overrides for gpgsql-password).
    {
      name = "pdns/daemonset.yaml";
      content = ''
        apiVersion: apps/v1
        kind: DaemonSet
        metadata:
          name: pdns-auth
          namespace: ${p.namespace}
          annotations:
            argocd.argoproj.io/sync-wave: "4"
          labels:
            app: pdns-auth
        spec:
          selector:
            matchLabels:
              app: pdns-auth
          template:
            metadata:
              labels:
                app: pdns-auth
            spec:
              hostNetwork: true
              dnsPolicy: ClusterFirstWithHostNet
              tolerations:
              - key: "node-role.kubernetes.io/control-plane"
                effect: "NoSchedule"
              initContainers:
              - name: template-config
                image: ${constants.registry.host}/library/busybox:1.36
                command:
                - sh
                - -c
                - |
                  while IFS= read -r line; do
                    line=''${line//\$(API_KEY)/$API_KEY}
                    line=''${line//\$(PG_PASSWORD)/$PG_PASSWORD}
                    printf '%s\n' "$line"
                  done < /etc/pdns-template/pdns.conf > /etc/pdns/pdns.conf
                env:
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: pdns-credentials
                      key: api-key
                - name: PG_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pdns-credentials
                      key: pg-password
                volumeMounts:
                - name: config-template
                  mountPath: /etc/pdns-template
                  readOnly: true
                - name: config-rendered
                  mountPath: /etc/pdns
              containers:
              - name: pdns
                image: ${p.image}
                args: ["--config-dir=/etc/pdns"]
                ports:
                - name: dns-udp
                  containerPort: ${toString p.dnsPort}
                  protocol: UDP
                - name: dns-tcp
                  containerPort: ${toString p.dnsPort}
                  protocol: TCP
                - name: api
                  containerPort: ${toString p.apiPort}
                  protocol: TCP
                securityContext:
                  runAsUser: 0
                  capabilities:
                    add: ["NET_BIND_SERVICE"]
                readinessProbe:
                  tcpSocket:
                    port: ${toString p.dnsPort}
                  initialDelaySeconds: 5
                  periodSeconds: 10
                livenessProbe:
                  tcpSocket:
                    port: ${toString p.dnsPort}
                  initialDelaySeconds: 10
                  periodSeconds: 30
                resources:
                  requests:
                    cpu: 50m
                    memory: 64Mi
                  limits:
                    cpu: 500m
                    memory: 256Mi
                volumeMounts:
                - name: config-rendered
                  mountPath: /etc/pdns
                  readOnly: true
              volumes:
              - name: config-template
                configMap:
                  name: pdns-config
              - name: config-rendered
                emptyDir: {}
      '';
    }

    # ─── LoadBalancer Service (VIP for stable DNS endpoint) ───────────
    {
      name = "pdns/service.yaml";
      content = ''
        apiVersion: v1
        kind: Service
        metadata:
          name: pdns-lb
          namespace: ${p.namespace}
          annotations:
            argocd.argoproj.io/sync-wave: "4"
          labels:
            app: pdns-auth
        spec:
          type: LoadBalancer
          loadBalancerIP: ${p.vip}
          selector:
            app: pdns-auth
          ports:
          - name: dns-udp
            port: ${toString p.dnsPort}
            targetPort: ${toString p.dnsPort}
            protocol: UDP
          - name: dns-tcp
            port: ${toString p.dnsPort}
            targetPort: ${toString p.dnsPort}
            protocol: TCP
      '';
    }

    # ─── Scoped LB IP pool + L2 policy (same pattern as registry) ────
    {
      name = "pdns/lb-ip-pool.yaml";
      content = ''
        apiVersion: cilium.io/v2
        kind: CiliumLoadBalancerIPPool
        metadata:
          name: pdns-lb-pool
        spec:
          serviceSelector:
            matchLabels:
              app: pdns-auth
          blocks:
          - start: "${p.vip}"
            stop:  "${p.vip}"
      '';
    }
    {
      name = "pdns/l2-announcement-policy.yaml";
      content = ''
        apiVersion: cilium.io/v2alpha1
        kind: CiliumL2AnnouncementPolicy
        metadata:
          name: pdns-l2
        spec:
          serviceSelector:
            matchLabels:
              app: pdns-auth
          interfaces:
          - ${constants.cilium.ingress.nic}
          externalIPs: true
          loadBalancerIPs: true
      '';
    }

    # ─── ArgoCD Application CR ────────────────────────────────────────
    {
      name = "pdns/application.yaml";
      content = ''
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: pdns
          namespace: argocd
        spec:
          project: default
          source:
            repoURL: ${constants.gitops.repoURL}
            targetRevision: ${constants.gitops.targetRevision}
            path: ${constants.gitops.renderedPath}/pdns
            directory:
              exclude: 'application.yaml'
          destination:
            server: https://kubernetes.default.svc
            namespace: ${p.namespace}
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - ServerSideApply=true
              - CreateNamespace=true
              - RespectIgnoreDifferences=true
          ignoreDifferences:
            - group: ""
              kind: Secret
              name: pdns-credentials
              namespace: ${p.namespace}
              jsonPointers: ["/data", "/stringData"]
      '';
    }
  ];
}
